service: API

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-west-1
  profile: default
  stage: dev

plugins:
  - serverless-offline

functions:
  playerController:
    handler: handler.handler
    events:
      - httpApi:
          path: /players
          method: get
      - httpApi:
          path: /players/{id}
          method: get
          request:
            parameters:
              paths:
              id: true
